apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-role-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: kane
  namespace: dev
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io
