apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-without-access-binding
subjects:
- kind: ServiceAccount
  name: dave
  namespace: default
roleRef:
  kind: ClusterRole
  name: role-without-access
  apiGroup: rbac.authorization.k8s.io
