{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.host }}
{{- end }}
